version: '3'
services:

  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: apache/kafka:latest
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
  
        	